---
title: "ST 558 Homework 3"
format: html
editor: visual
---

Reading in previous code
```{r}
load("hw2_list.rda")
```

## Task 1
Creating new columns for both data frames
```{r}
bp_list$treatment$status <- character(20)
bp_list$placebo$status <- character(10)
```

Filling the new columns with values
```{r}
for (i in 1:20) {
  if (bp_list$treatment$post_bp[i] > 130) {
    bp_list$treatment$status[i] = "high"
  } else if (bp_list$treatment$post_bp[i] <= 130 & bp_list$treatment$post_bp[i] > 120) {
    bp_list$treatment$status[i] = "borderline"
  } else if (bp_list$treatment$post_bp[i] <= 120) {
    bp_list$treatment$status[i] = "optimal"
  } else {
    bp_list$treatment$status[i] = "error"
  }
}
```

```{r}
for (i in 1:10) {
  if (bp_list$placebo$post_bp[i] > 130) {
    bp_list$placebo$status[i] = "high"
  } else if (bp_list$placebo$post_bp[i] <= 130 & bp_list$placebo$post_bp[i] > 120) {
    bp_list$placebo$status[i] = "borderline"
  } else if (bp_list$placebo$post_bp[i] <= 120) {
    bp_list$placebo$status[i] = "optimal"
  } else {
    bp_list$placebo$status[i] = "error"
  }
}
```

## Task 2
Function Writing
```{r}
list_fun <- function(df_list, stat = "mean") {
  my_fun <- get(stat)
  
  treat_pre <- my_fun(df_list$treatment$pre)
  treat_post <- my_fun(df_list$treatment$post)
  treat_diff <- my_fun(df_list$treatment$diff)
  
  plac_pre <- my_fun(df_list$placebo$pre)
  plac_post <- my_fun(df_list$placebo$post)
  plac_diff <- my_fun(df_list$placebo$diff)
  
  stat_vec <- c(treat_pre, treat_post, treat_diff, plac_pre, plac_post, plac_diff)
  
  names_vec <- c("treat_pre", "treat_post", "treat_diff", "plac_pre", "plac_post", "plac_diff")
  for (i in 1:6) {
    names_vec[i] = paste0(names_vec[i], "_", stat)
  }
  
  names(stat_vec) <- names_vec
  
  return(stat_vec)
}
```

Testing the function
```{r}
list_fun(bp_list)
list_fun(bp_list, "max")
```

